# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-24 08:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0004_auto_20181023_0820'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='address',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='phone',
        ),
    ]
