# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-27 15:38
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0007_auto_20181027_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=ckeditor.fields.RichTextField(max_length=2000),
        ),
    ]
