# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-27 15:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0008_auto_20181027_1538'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=models.CharField(max_length=2000),
        ),
    ]
