# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-28 12:43
from __future__ import unicode_literals

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0011_auto_20181027_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
