# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-28 14:11
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0012_auto_20181028_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='description',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
    ]
