# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-28 15:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0013_auto_20181028_1411'),
    ]

    operations = [
        migrations.AddField(
            model_name='gig',
            name='songfile',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
