# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-28 16:33
from __future__ import unicode_literals

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0014_gig_songfile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gig',
            old_name='description',
            new_name='answers',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='photo',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='price',
        ),
        migrations.RemoveField(
            model_name='gig',
            name='title',
        ),
        migrations.AddField(
            model_name='gig',
            name='tasks',
            field=ckeditor.fields.RichTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='gig',
            name='songfile',
            field=models.FileField(blank=True, upload_to='songs'),
        ),
    ]
