# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-28 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0015_auto_20181028_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('1', 'ЕГЭ:Английский язык'), ('2', 'IELTS'), ('3', 'TOEFL')], max_length=2),
        ),
    ]
