# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-30 11:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0016_auto_20181028_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('ЕГЭ:Английский язык', 'ЕГЭ:Английский язык'), ('IELTS', 'IELTS'), ('TOEFL', 'TOEFL')], max_length=2),
        ),
    ]
