# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-10-30 12:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0019_auto_20181030_1211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('ЕГЭ егэ английский Английский Язык язык', 'ЕГЭ:Английский язык'), ('IELTS ielts шудеы', 'IELTS'), ('TOEFL toefl ещуад', 'TOEFL')], max_length=50),
        ),
    ]
