# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-11-26 10:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0025_auto_20181126_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='task_logo/'),
        ),
    ]
