# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-02-07 13:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0027_profile_philosopher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gig',
            name='category',
            field=models.CharField(choices=[('ЕГЭ егэ английский Английский Язык язык', 'История западной философии'), ('IELTS ielts шудеы', 'Философвские взгляды'), ('TOEFL toefl ещуад', 'Биография'), ('TOEFL toefl ещуад', 'Математическая логика'), ('TOEFL toefl ещуад', 'Иное')], max_length=50),
        ),
    ]
