# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2019-05-29 08:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('taskerapp', '0029_auto_20190529_0809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='philosopher',
        ),
    ]
